services:
  app:
    build: .
    container_name: sveltekit_app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/windyspoon.com.pem:/etc/ssl/certs/windyspoon.com.pem:ro
      - ./nginx/windyspoon.com.key:/etc/ssl/private/windyspoon.com.key:ro
    depends_on:
      - app
